# Generated by Django 5.1.6 on 2025-05-14 10:14

import django.db.models.deletion
import django.utils.timezone
import myApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('people', models.IntegerField()),
                ('estimated_arrival_time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('booked_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
            ],
        ),
        migrations.CreateModel(
            name='APLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_datetime', models.DateTimeField()),
                ('po_id', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_ordered', models.IntegerField()),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('people_count', models.IntegerField()),
                ('estimated_time', models.TimeField()),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In-Session', 'In-Session'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('purchase_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_ordered', models.IntegerField()),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Gcash', 'Gcash'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash', max_length=50)),
                ('order_status', models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return to Supplier', 'Return to Supplier'), ('Checking', 'Checking'), ('Completed', 'Completed')], default='Unclaimed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RemovedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_transaction_id', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(max_length=20)),
                ('date_removed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('admin_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('stocks_added', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.TextField(unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.TextField()),
                ('customer_address', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('people', models.IntegerField()),
                ('estimated_arrival_time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('booked_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UTlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('delivery_address', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('removed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[myApp.models.validate_com_email])),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedTrackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myApp.deletedtracking')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.admininventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Store Pick-up', 'Store Pick-up'), ('Cash On Delivery', 'Cash On Delivery'), ('Card Payment', 'Card Payment')], max_length=50)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myApp.tracking')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myApp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UTlogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myApp.utlogs')),
            ],
        ),
    ]
