# Generated by Django 5.1.6 on 2025-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='source',
            field=models.CharField(default='ordering', max_length=20),
        ),
    ]
